apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: Jenkins-demo
    app.kubernetes.io/instance: Jenkins-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: eksapp
  namespace: eksapp
spec:
  selector:
    app: eksapp
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 8080
      targetPort: 4000
